### ISSUE TITLE
Default Theme not up to date

### ISSUE THREAD

**Issue by knutsp** [wp-healthcheck/wp-healthcheck#45]
When going to troubleshooting mode without Twenty Nineteen, with Twenty Twenty, it complains that no default theme is installed and offers to install one, which comes up as Twenty Nineteen.

Isn't it a WP constant saying which is the default theme? Is this hard coed in this plugin? Should be fixed and kept up to date, as it's annoying to have to install Twenty Nineteen again to get full troubleshooting.

BTW: The email sending tool is very good, as it tells when there is an error using wp_mail(). This happens with PHP 7.4 on some cPanel servers.

**Comment by tiagohillebrandt** [comment]
@knutsp This repository is focused on WP Healthcheck plugin development, which is a different plugin than Health Check.

You may want to share your comment with the Health Check team over here: https://wordpress.org/support/plugin/health-check/
